---
deployment:
  tasks:
    - export DEPLOYPATH=/home/konnectinitiativ/public_html/system
    - /bin/rsync -av --exclude='.git' --exclude='.env' --exclude='storage/logs' --exclude='storage/framework' --exclude='public/.htaccess' . $DEPLOYPATH
